---
#
#    CentOS 6 (centos6) docker-compose.yml
#    Copyright (C) 2016 SOL-ICT
#    This file is part of the Docker General Purpose System Distro.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services/profiles
#
services:

  base:
    labels:
      - "${service_base_label_url}.description=${service_base_description}"
      - "${service_base_label_url}.vendor=${project_vendor}"
      - "${service_base_label_url}.license=${project_license}"
      - "${service_base_label_url}.architecture=${project_architecture}"
      - "${service_base_label_url}.version=${project_version}"
    image: "${service_base_image_url}"
    build:
      context: "${general_context}"
      dockerfile: "${service_base_dockerfile}"
      args:
        app_dropbear_listen_addr: "${service_base_args_app_dropbear_listen_addr}"
        app_dropbear_listen_port: "${service_base_args_app_dropbear_listen_port}"
        app_dropbear_key_size: "${service_base_args_app_dropbear_key_size}"
    logging:
      driver: "${general_logging_driver}"
    ports:
      - "${service_base_networking_port_int1}"
    working_dir: "${general_working_dir}"
    command: "${service_base_command}"

  devel:
    labels:
      - "${service_devel_label_url}.description=${service_devel_description}"
      - "${service_devel_label_url}.vendor=${project_vendor}"
      - "${service_devel_label_url}.license=${project_license}"
      - "${service_devel_label_url}.architecture=${project_architecture}"
      - "${service_devel_label_url}.version=${project_version}"
    image: "${service_devel_image_url}"
    build:
      context: "${general_context}"
      dockerfile: "${service_devel_dockerfile}"
    logging:
      driver: "${general_logging_driver}"
    ports:
      - "${service_devel_networking_port_int1}"
    working_dir: "${general_working_dir}"
    command: "${service_devel_command}"

