---
#
#    CentOS 7 (centos7) docker-compose.yml
#    Copyright (C) 2016 SOL-ICT
#    This file is part of the Docker General Purpose System Distro.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Main services
#
services:

  minimal:
    labels:
      - "org.sol-ict.general.purpose.system.distro.centos7_minimal.description=General Purpose System Distro - Minimal profile, based on CentOS 7 (centos7)"
      - "org.sol-ict.general.purpose.system.distro.centos7_minimal.vendor=SOL-ICT"
      - "org.sol-ict.general.purpose.system.distro.centos7_minimal.license=GPLv3"
      - "org.sol-ict.general.purpose.system.distro.centos7_minimal.architecture=amd64"
      - "org.sol-ict.general.purpose.system.distro.centos7_minimal.version=1.0"
    image: "solict/general-purpose-system-distro:centos7_minimal"
    build:
      context: "./dockerfiles"
      dockerfile: "minimal.dockerfile"
    logging:
      driver: "json-file"
    working_dir: "/tmp"
    command: "/bin/bash"

  standard:
    labels:
      - "org.sol-ict.general.purpose.system.distro.centos7_standard.description=General Purpose System Distro - Standard profile, based on Minimal"
      - "org.sol-ict.general.purpose.system.distro.centos7_standard.vendor=SOL-ICT"
      - "org.sol-ict.general.purpose.system.distro.centos7_standard.license=GPLv3"
      - "org.sol-ict.general.purpose.system.distro.centos7_standard.architecture=amd64"
      - "org.sol-ict.general.purpose.system.distro.centos7_standard.version=1.0"
    image: "solict/general-purpose-system-distro:centos7_standard"
    build:
      context: "./dockerfiles"
      dockerfile: "standard.dockerfile"
      args:
        app_dropbear_listen_addr: "0.0.0.0"
        app_dropbear_listen_port: "22"
        app_dropbear_key_size: "4096"
    depends_on:
      - minimal
    logging:
      driver: "json-file"
    ports:
      - "22"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

  devel:
    labels:
      - "org.sol-ict.general.purpose.system.distro.centos7_devel.description=General Purpose System Distro - Devel profile, based on Development"
      - "org.sol-ict.general.purpose.system.distro.centos7_devel.vendor=SOL-ICT"
      - "org.sol-ict.general.purpose.system.distro.centos7_devel.license=GPLv3"
      - "org.sol-ict.general.purpose.system.distro.centos7_devel.architecture=amd64"
      - "org.sol-ict.general.purpose.system.distro.centos7_devel.version=1.0"
    image: "solict/general-purpose-system-distro:centos7_devel"
    build:
      context: "./dockerfiles"
      dockerfile: "devel.dockerfile"
    depends_on:
      - standard
    logging:
      driver: "json-file"
    ports:
      - "22"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

